// GENERATED by scripts/brand/render_brand.mjs — do not edit by hand; re-run the script.
//
// The line boxes of the wordmark images (assets/brand/wordmark.png, r_mark.png) in logical pixels, measured in the same
// rendering the images were cut from (Literata 600, opsz 72, 44/48, tracking −0.01em — frame 41-1).

/// Width of the «Ritora» line box — the image's logical width.
const double kWordmarkWidth = 133.06;

/// Height of both line boxes — the 48 of «44/48».
const double kWordmarkHeight = 48;

/// Width of the «R» line box alone — frame 41-1a centres this box, and so does the launch screen.
const double kWordmarkRWidth = 31.11;

/// The word's images are whole logical pixels wide (a screenshot clip snaps up), the glyphs at x 0 — the extra
/// fraction is empty on the right. r_mark.png is wider than its «R»: the leg overhangs the advance, so the box sits
/// [kRMarkInset] in, with the same air on the left, and the launch screen can centre the image.
const double kWordmarkImageWidth = 134;
const double kRMarkImageWidth = 48;

/// The «R» box starts this far inside r_mark.png (8 px of air for its leg on the right, the same on the left).
const double kRMarkInset = 8;

/// Where letters 1…5 («i», «t», «o», «r», «a») start inside the word box — the splash reveals the word by these cuts.
const List<double> kWordmarkLetterStarts = [31.09, 45.05, 61.81, 87.77, 109.16];
