<?php

declare(strict_types=1);

use App\Modules\Generation\Application\Service\ContentContract;
use App\Modules\Generation\Domain\Service\EnrichmentValidator;
use App\Modules\Generation\Domain\ValueObject\EnrichmentCandidate;
use App\Modules\Generation\Domain\ValueObject\PromptShape;
use App\Modules\Generation\Domain\ValueObject\RawDistractor;
use App\Modules\Generation\Infrastructure\Prompt\PromptLibrary;

function machinery(string $version): string
{
    return (new PromptLibrary())->render($version, PromptShape::Machinery, [
        'source_lang' => 'Russian',
        'target_lang' => 'English',
    ])->text;
}

it('asks v12.1 for four or five candidates where v12 asked for two or three', function () {
    expect(machinery('v12.1'))
        ->toContain('4–5 wrong versions of the card')
        ->toContain('Propose CANDIDATES, not a finished set.')
        ->toContain('This is an over-order, **not a quota.**')
        // The count is where a card STARTS, and the self-check says so where the discarding happens.
        ->toContain('the count is what you START with, never what you must end with');

    // v12 is frozen: it is what the run-in collections were generated by, and an edit to it would
    // move the rendered bytes under a `generator_version` already recorded on live rows.
    expect(machinery('v12'))
        ->toContain('2–3 wrong versions of the card')
        ->not->toContain('Propose CANDIDATES, not a finished set.');
});

it('keeps every honesty rule that makes the over-order safe', function () {
    // «Пустые формы лучше набивки» — the whole reason a bigger ask is not a bigger risk.
    expect(machinery('v12.1'))
        ->toContain('Return an empty list rather than padding.')
        ->toContain('It must be **genuinely incorrect**')
        ->toContain('It must **not** be a correct answer in disguise.')
        ->toContain('Never change the MEANING.')
        ->toContain('If you find only one honest error in')
        ->toContain('If a card\'s example is missing or too short to damage in one place, return an empty list');
});

it('lets the schema carry five candidates while the store still keeps three', function () {
    $schema = app(ContentContract::class)->schema(PromptShape::Machinery);
    $distractors = $schema['properties']['items']['items']['properties']['distractors'];

    // The ask is the wider of the two on purpose: the validator scraps roughly half, so a schema
    // capped at what a card holds is a card that ends up holding less.
    expect($distractors['maxItems'])->toBe(5)
        ->and(EnrichmentValidator::MAX_DISTRACTORS)->toBe(3);
});

it('still stores at most three, taking the first three that survive', function () {
    $example = 'I need a bank account to receive my salary.';
    $raw = [
        // Four honest ones…
        new RawDistractor('I need bank account to receive my salary.', 'article', 'need bank account', 'need a bank account'),
        new RawDistractor('I need a bank account to receive my salary at.', 'preposition', 'salary at', 'salary'),
        new RawDistractor('I needs a bank account to receive my salary.', 'tense', 'needs', 'need'),
        new RawDistractor('I need a bank account for receive my salary.', 'modal_to', 'for receive', 'to receive'),
        // …and one that is secretly the example. It never had a chance, over-order or not.
        new RawDistractor($example, 'article', 'a bank', 'a bank'),
    ];

    $verdict = (new EnrichmentValidator())->validate(new EnrichmentCandidate(
        termId: '01J0TERM',
        acceptedForms: ['bank account'],
        exampleId: '01J0EXAMPLE',
        exampleSentence: $example,
        translation: 'банковский счёт',
        exampleTranslation: 'Мне нужен банковский счёт, чтобы получать зарплату.',
        distractors: $raw,
        variants: [],
        backTranslation: null,
        languageNotes: [],
        backTranslationAsked: false,
    ));

    expect($verdict->distractors)->toHaveCount(EnrichmentValidator::MAX_DISTRACTORS)
        ->and($verdict->proposedDistractors)->toBe(5);
});
