import 'dart:convert';
import 'dart:io';

import 'package:eng_std/data/models.dart';
import 'package:eng_std/data/practice/practice_mode_selector.dart';
import 'package:flutter_test/flutter_test.dart';

/// The contract between this port and the server's `ExerciseSelector::selectForPractice`.
///
/// Free practice is built on the device, so the mode ladder exists twice. A divergence would be
/// silent — the card would simply be the wrong exercise and nothing would fail — so the fixture is
/// generated BY the server's own selector and read here unchanged. There is deliberately no copy
/// of it in this package: one file, two readers, no way for them to drift apart quietly.
///
/// Regenerate after a server-side ladder change:
///
///     docker compose exec -e EXPORT_PRACTICE_FIXTURE=1 app php artisan test --filter=practice_contract
void main() {
  final file = File('../backend2/tests/Fixtures/practice-mode-contract.json');

  test('the fixture is present (the contract has a source of truth)', () {
    expect(
      file.existsSync(),
      isTrue,
      reason: 'missing ${file.path} — regenerate it with EXPORT_PRACTICE_FIXTURE=1 (see the header)',
    );
  });

  final fixture = jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
  final enabled = PracticeModes([
    for (final wire in (fixture['enabled_modes'] as List).cast<String>()) ExerciseMode.fromWire(wire),
  ]);
  final cases = (fixture['cases'] as List).cast<Map<String, dynamic>>();

  test('the enabled set and its ORDER match the server config', () {
    // The rotation indexes into this list, so a reordering re-deals every card.
    expect(
      enabled.modes.map((m) => m.wire).toList(),
      PracticeModes.serverDefault.modes.map((m) => m.wire).toList(),
    );
  });

  test('the rotation seed matches (card index + crc32 of the term id)', () {
    for (final c in cases) {
      expect(
        PracticeModeSelector.rotationFor(c['term_id'] as String, c['card_index'] as int),
        c['rotation'],
        reason: 'seed drift on ${c['term_id']} @${c['card_index']} — crc32 or the formula',
      );
    }
  });

  test('word count and clozeable are derived the same way', () {
    for (final c in cases) {
      final answer = c['answer'] as String;
      expect(PracticeModeSelector.answerWordCount(answer), c['word_count'],
          reason: 'word count drift on "$answer" — this gates word_bank');
      expect(PracticeModeSelector.clozeable(answer, c['example'] as String?), c['clozeable'],
          reason: 'clozeable drift on "$answer" — this gates cloze');
    }
  });

  test('every case picks the mode the server picked', () {
    for (final c in cases) {
      final picked = PracticeModeSelector.select(
        enabled: enabled,
        rotation: c['rotation'] as int,
        answerWordCount: c['word_count'] as int,
        clozeable: c['clozeable'] as bool,
      );
      expect(picked.wire, c['expected_mode'],
          reason: 'mode drift on ${c['term_id']} @${c['card_index']} ("${c['answer']}")');
    }
  });

  test('the whole chain agrees end to end, from term id to mode', () {
    // The previous tests pin each step; this one pins them composed, which is how the builder
    // actually calls it — a compensating pair of bugs would survive the parts but not this.
    for (final c in cases) {
      final answer = c['answer'] as String;
      final picked = PracticeModeSelector.select(
        enabled: enabled,
        rotation: PracticeModeSelector.rotationFor(c['term_id'] as String, c['card_index'] as int),
        answerWordCount: PracticeModeSelector.answerWordCount(answer),
        clozeable: PracticeModeSelector.clozeable(answer, c['example'] as String?),
      );
      expect(picked.wire, c['expected_mode']);
    }
  });

  test('a mode the config does not enable is never dealt', () {
    // The phase-1 set: no listening, no cloze. Mirrors the server's own guard.
    const phase1 = PracticeModes([
      ExerciseMode.multipleChoice,
      ExerciseMode.wordBank,
      ExerciseMode.typing,
    ]);
    final dealt = <String>{};
    for (var rotation = 0; rotation < 60; rotation++) {
      dealt.add(PracticeModeSelector.select(
        enabled: phase1,
        rotation: rotation,
        answerWordCount: 3,
        clozeable: true,
      ).wire);
    }

    expect(dealt, {'multiple_choice', 'word_bank', 'typing'});
  });

  test('a negative seed still maps into range', () {
    expect(
      () => PracticeModeSelector.select(
        enabled: enabled,
        rotation: -1,
        answerWordCount: 3,
        clozeable: true,
      ),
      returnsNormally,
    );
  });
}
