import 'dart:convert';
import 'dart:io';

import 'package:eng_std/data/models.dart';
import 'package:eng_std/data/practice/practice_mode_selector.dart';
import 'package:flutter_test/flutter_test.dart';

/// The contract between this port and the server's `ExerciseSelector::selectForPractice`.
///
/// Free practice is built on the device, so the mode ladder exists twice. A divergence would be
/// silent — the card would simply be the wrong exercise and nothing would fail — so the fixture is
/// generated BY the server's own selector and read here unchanged. There is deliberately no copy
/// of it in this package: one file, two readers, no way for them to drift apart quietly.
///
/// Regenerate after a server-side ladder change:
///
///     docker compose exec -e EXPORT_PRACTICE_FIXTURE=1 app php artisan test --filter=practice_contract
void main() {
  final file = File('../backend2/tests/Fixtures/practice-mode-contract.json');

  test('the fixture is present (the contract has a source of truth)', () {
    expect(
      file.existsSync(),
      isTrue,
      reason:
          'missing ${file.path} — regenerate it with EXPORT_PRACTICE_FIXTURE=1 (see the header)',
    );
  });

  final fixture = jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
  final enabled = PracticeModes([
    for (final wire in (fixture['enabled_modes'] as List).cast<String>())
      ExerciseMode.fromWire(wire),
  ]);
  final cases = (fixture['cases'] as List).cast<Map<String, dynamic>>();

  test('the enabled set and its ORDER match the server config', () {
    // The rotation indexes into this list, so a reordering re-deals every card.
    expect(
      enabled.modes.map((m) => m.wire).toList(),
      PracticeModes.serverDefault.modes.map((m) => m.wire).toList(),
    );
  });

  test('the rotation seed matches (card index + crc32 of the term id)', () {
    for (final c in cases) {
      expect(
        PracticeModeSelector.rotationFor(c['term_id'] as String, c['card_index'] as int),
        c['rotation'],
        reason: 'seed drift on ${c['term_id']} @${c['card_index']} — crc32 or the formula',
      );
    }
  });

  /// The gate inputs, derived here exactly as the server's PlayabilityAssessor derived them.
  TermPlayability playabilityOf(Map<String, dynamic> c) => TermPlayability.of(
    answer: c['answer'] as String,
    example: c['example'] as String?,
    exampleTranslation: c['example_translation'] as String?,
  );

  test('every gate input is derived the same way', () {
    // One assertion per input, so a drift names the gate it breaks instead of just "wrong mode".
    for (final c in cases) {
      final answer = c['answer'] as String;
      final p = playabilityOf(c);
      expect(
        p.answerWordCount,
        c['word_count'],
        reason: 'word count drift on "$answer" — this gates word_bank',
      );
      expect(
        p.answerCharCount,
        c['answer_char_count'],
        reason: 'letter count drift on "$answer" — this is the other half of the word_bank gate',
      );
      expect(
        p.clozeable,
        c['clozeable'],
        reason: 'clozeable drift on "$answer" — this gates cloze',
      );
      expect(
        p.exampleTokenCount,
        c['example_token_count'],
        reason: 'tokenizer drift on "${c['example']}" — this gates scramble length',
      );
      expect(
        p.hasExampleTranslation,
        c['has_example_translation'],
        reason: 'translation gate drift on "$answer"',
      );
      expect(
        p.exampleIsAnswer,
        c['example_is_answer'],
        reason:
            'example-is-the-term drift on "$answer" — this keeps scramble off word_bank\'s turf',
      );
    }
  });

  test('the gates agree for EVERY mode, including ones nobody has enabled', () {
    // `enabled_modes` is the shipped default, so a trainer released switched off (the release rule
    // in CLAUDE.md) never appears in `expected_mode` and its gate would go unpinned until the day
    // it is turned on — which is the worst possible day to discover a divergence. This asserts the
    // applicability itself, which depends on the term's data and not on anyone's toggles.
    for (final c in cases) {
      final p = playabilityOf(c);
      // Graded modes only, exactly as the fixture is generated. `intro` is applicable to every term
      // by construction (it asks for nothing, so no content can be missing) and is never dealt in
      // practice, so listing it would add a constant to both sides rather than a fact about a term.
      final supported = [
        for (final mode in ExerciseMode.values)
          if (mode.isGraded && p.supports(mode)) mode.wire,
      ];

      expect(
        supported,
        (c['supported_modes'] as List).cast<String>(),
        reason: 'gate drift on "${c['answer']}" / "${c['example']}"',
      );
    }
  });

  test('every case picks the mode the server picked', () {
    for (final c in cases) {
      final picked = PracticeModeSelector.select(
        enabled: enabled,
        rotation: c['rotation'] as int,
        playable: TermPlayability(
          answerWordCount: c['word_count'] as int,
          answerCharCount: c['answer_char_count'] as int,
          clozeable: c['clozeable'] as bool,
          exampleTokenCount: c['example_token_count'] as int,
          hasExampleTranslation: c['has_example_translation'] as bool,
          exampleIsAnswer: c['example_is_answer'] as bool,
        ),
      );
      expect(
        picked.wire,
        c['expected_mode'],
        reason: 'mode drift on ${c['term_id']} @${c['card_index']} ("${c['answer']}")',
      );
    }
  });

  test('the whole chain agrees end to end, from term id to mode', () {
    // The previous tests pin each step; this one pins them composed, which is how the builder
    // actually calls it — a compensating pair of bugs would survive the parts but not this.
    for (final c in cases) {
      final picked = PracticeModeSelector.select(
        enabled: enabled,
        rotation: PracticeModeSelector.rotationFor(c['term_id'] as String, c['card_index'] as int),
        playable: playabilityOf(c),
      );
      expect(picked.wire, c['expected_mode']);
    }
  });

  test('a mode the config does not enable is never dealt', () {
    // The phase-1 set: no listening, no cloze. Mirrors the server's own guard.
    const phase1 = PracticeModes([
      ExerciseMode.multipleChoice,
      ExerciseMode.wordBank,
      ExerciseMode.typing,
    ]);
    final dealt = <String>{};
    for (var rotation = 0; rotation < 60; rotation++) {
      dealt.add(
        PracticeModeSelector.select(
          enabled: phase1,
          rotation: rotation,
          playable: const TermPlayability(answerWordCount: 3, clozeable: true),
        ).wire,
      );
    }

    expect(dealt, {'multiple_choice', 'word_bank', 'typing'});
  });

  test('a negative seed still maps into range', () {
    expect(
      () => PracticeModeSelector.select(
        enabled: enabled,
        rotation: -1,
        playable: const TermPlayability(answerWordCount: 3, clozeable: true),
      ),
      returnsNormally,
    );
  });
}
