import 'dart:async';

import 'package:flutter/foundation.dart';

import '../data/audio_mixer.dart';
import 'haptics.dart';

/// SOUND AND HAPTIC — ONE SERVICE for every screen of the old training (token list 4к-3, 4е; work order DAY-UI).
///
/// Four events and no more: correct · wrong · stage closed · day closed. Each is the haptic first, then the sound,
/// from one place, because they always go together.
///
/// The sounds are OURS, generated by `tool/gen_feedback_sounds.dart` into `assets/sounds/`, and play as short sounds
/// of the app's one audio engine ([AudioMixer], work order SESSION-2a §1): mixed over speech at [AudioLevels.effect],
/// never stopping it.
///
/// The «Sounds» switch in the profile is [soundsEnabled]; the settings provider sets it. The haptic never depends on
/// it.
abstract final class AppFeedback {
  /// «Звуки» in the profile (4к-3). Flipped by the settings controller; the haptic never depends on it.
  static bool soundsEnabled = true;

  /// The asset base names, which are also the names the engine keeps them under.
  @visibleForTesting
  static const String correctSound = 'verdict_correct';
  @visibleForTesting
  static const String wrongSound = 'verdict_wrong';
  @visibleForTesting
  static const String stageClosedSound = 'stage_closed';
  @visibleForTesting
  static const String dayClosedSound = 'day_closed';

  /// «Верно» — a short soft tone up, 120 ms. Haptic success.
  static void correct() {
    AppHaptics.success();
    _play(correctSound);
  }

  /// «Неверно» — low and muffled, 160 ms: a soft «no», not an error signal. Haptic warning.
  static void wrong() {
    AppHaptics.warning();
    _play(wrongSound);
  }

  /// «Этап закрыт» — two notes up, 240 ms. Haptic success.
  static void stageClosed() {
    AppHaptics.success();
    _play(stageClosedSound);
  }

  /// «День закрыт» — three notes up, 300 ms. Haptic success once; no confetti.
  static void dayClosed() {
    AppHaptics.success();
    _play(dayClosedSound);
  }

  /// Fire and forget: a verdict is never held up by its own sound effect.
  static void _play(String sound) {
    if (!soundsEnabled) return;
    unawaited(AudioMixer.playEffect(sound, 'assets/sounds/$sound.wav'));
  }
}

/// THE DAY SESSION'S SOUNDS (SESSION-1b′, item 5; the owner's files and decisions of 16.09) — the owner's six mp3 in
/// `assets/sounds/`, wired by the owner's map:
///
/// * [correct] / [miss] — the 30-4 reactions (choice, tiles) and the verdict of the voice and of the slot judge;
/// * [micOn] — a recording starts;
/// * [stageDone] — a stage summary opens;
/// * [dayDone] — the day summary (30-7) opens;
/// * [ready] — the day is ready after waiting for its lesson to be built.
///
/// Short sounds of the app's one audio engine ([AudioMixer], SESSION-2a §1): [load] decodes the six when the session
/// opens (leading silence cut, the asset files untouched), [release] frees them when it closes; each plays at
/// [AudioLevels.effect] over the speech and never stops it. «Sounds in the session» off — nothing is loaded or played.
abstract final class SessionSounds {
  static const String correct = 'correct';
  static const String miss = 'miss';
  static const String micOn = 'mic_on';
  static const String stageDone = 'stage_done';
  static const String dayDone = 'day_done';
  static const String ready = 'ready';

  static const List<String> all = [correct, miss, micOn, stageDone, dayDone, ready];

  static String _asset(String sound) => 'assets/sounds/$sound.mp3';

  /// «Sounds in the session» — set by the settings controller.
  static bool get enabled => _enabled;
  static bool _enabled = true;
  static bool _loaded = false;

  static set enabled(bool on) {
    _enabled = on;
    if (!on && _loaded) unawaited(release());
  }

  /// The session opened: decode the six sounds — unless «Sounds in the session» is off.
  static Future<void> load() async {
    if (!_enabled || _loaded) return;
    _loaded = true;
    final count = await AudioMixer.loadEffects({for (final s in all) s: _asset(s)});
    debugPrint('[session-sounds] decoded $count of ${all.length}');
  }

  /// The session closed: free the decoded sounds.
  static Future<void> release() async {
    if (!_loaded) return;
    _loaded = false;
    await AudioMixer.releaseEffects(all);
  }

  /// Play one of the six. Not loaded (switch off, no session) — silence.
  static void play(String sound) {
    if (!_enabled || !_loaded) return;
    unawaited(AudioMixer.playEffect(sound, _asset(sound)));
  }

  /// The reaction to an answer: «correct» or «miss».
  static void verdict({required bool correct}) => play(correct ? SessionSounds.correct : miss);

  /// «Day done» — the day summary opens.
  static void dayCompleted() => play(dayDone);

  @visibleForTesting
  static void resetForTest() {
    _enabled = true;
    _loaded = false;
  }
}
