import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import 'haptics.dart';

/// The verdict's sound + haptic, as one call — the moment an answer is judged, in EVERY practice
/// mode (the verdict is shared, so this is not a speaking-only affordance).
///
/// Sound and haptic are deliberately one thing rather than two: they always fire together, at
/// exactly one place ([SessionExerciseCard]'s commit), and splitting them is how a mode ends up
/// buzzing without a sound or the reverse.
///
/// The sounds are OURS (QA-22), generated by `tool/gen_feedback_sounds.dart` into `assets/sounds/`
/// and played natively — see [_channel]. The system set was tried first and is genuinely two
/// sounds wide on iOS ([SystemSoundType.alert] is documented desktop-only and simply does not play
/// there), so «верно» and «не то» came out as two nearly identical UI ticks: too quiet on the
/// device, and carrying none of the difference the verdict is about. Two generated tones cost one
/// method channel and ~35 KB, and no pub dependency.
///
/// Silent switch: still respected, and still for free. The native side plays these through
/// `AudioServicesPlaySystemSound`, the same system-sound path [SystemSound] used — a silenced
/// phone plays nothing and the haptic still fires, which is exactly the wanted behaviour, so
/// nothing here checks the switch itself.
abstract final class AppFeedback {
  /// Handled in `ios/Runner/AppDelegate.swift`. Android has no handler and would throw
  /// [MissingPluginException]; that is caught below rather than guarded by a platform check,
  /// because the app is iOS-only and the failure mode that matters is «a sound must never take an
  /// answer down with it», not «which OS is this».
  @visibleForTesting
  static const MethodChannel channel = MethodChannel('com.denis.engstd/feedback_sound');

  /// The asset base names, which are also the identifiers the native side accepts.
  @visibleForTesting
  static const String correctSound = 'verdict_correct';
  @visibleForTesting
  static const String wrongSound = 'verdict_wrong';

  /// An accepted answer — «Верно» and «Почти» alike. Both are answers the scheduler counts, so
  /// giving «Почти» the wrong-answer feel would contradict the verdict shown right next to it.
  ///
  /// A warm rising major duplet (E5 → G#5, ~180 ms).
  static void correct() {
    AppHaptics.success();
    _play(correctSound);
  }

  /// A wrong answer. Softer, not punitive: this trainer's whole speaking design is about not
  /// making someone flinch at getting something wrong out loud.
  ///
  /// One low tone easing downward (A3, ~210 ms), quieter than [correct].
  static void wrong() {
    AppHaptics.warning();
    _play(wrongSound);
  }

  /// Fire and forget. A verdict is never held up by its own sound effect, and a sound that fails
  /// to play is not something the learner can act on — so the failure is swallowed here rather
  /// than surfaced anywhere.
  static void _play(String sound) {
    channel.invokeMethod<void>('play', {'sound': sound}).catchError((Object e) {
      debugPrint('[feedback] $sound did not play: $e');
    });
  }
}
